app/models.py
from . import db
from datetime import datetime
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin,current_user
from . import login_manager






class User(UserMixin,db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),index = True) 
    email = db.Column(db.String(255),unique = True,index = True)
    role_id = db.Column(db.Integer,db.ForeignKey('roles.id'))
    posts = db.relationship('Post', backref='author', lazy=True)
    comment = db.relationship('Comment', backref='author', lazy=True)
    pass_secure = db.Column(db.String(255))

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)

    def save(self):
        db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()

    def __repr__(self):
            return f'User: {self.username} Email: {self.email}'

@login_manager.user_loader
def user_loader(user_id):
    return User.query.get(user_id)

class Role(db.Model):
    __tablename__ = 'roles'

    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(255))
    users = db.relationship('User',backref = 'role',lazy="dynamic") 

    def __repr__(self):
        return f'User {self.name}'

class Post(db.Model):
    __tablename__ = 'posts'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String, nullable=False)
    date_posted = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    content = db.Column(db.Text, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))

    def save(self):
        db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()

    def __repr__(self):
        return f'Post title: {self.title}, Date Posted: {self.date_posted}, Post Content: {self.content}'


class Comment(db.Model):
    __tablename__ = 'comments'
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    post_id = db.Column(db.Integer, db.ForeignKey('posts.id'))
    comment = db.Column(db.Text())

    def save(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comments(cls, post_id):
        comments = Comment.query.filter_by(post_id=post_id).all()
        return comments

    def delete(self):
        db.session.delete(self)
        db.session.commit()

    def __repr__(self):
        return f'Comments: {self.comment}'

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField, SelectField, RadioField
from wtforms.validators import Required
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

app/__init__.py
from flask import Flask
from config import config_options
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_mail import Mail

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()
mail = Mail()


def create_app(config_name):

    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    # Initializing Flask Extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,errors

app/main/views.py
import os

from flask import render_template,request, redirect, url_for, abort,flash
from . import main
from .forms import PostForm
from ..models import Post,Comment
from .. import db
from app.requests import getQuotes
from flask_login import login_required,current_user

# Views
@main.route('/')
def index():

    '''
    View root page function that returns the index page and its data
    '''
    quotes=getQuotes()
    posts = Post.query.all()
    title='Quotes Blog'
    return render_template('index.html',title=title,quotes=quotes,posts=posts, current_user=current_user)



@main.route("/new_post", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data,author=current_user)
        post.save()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.index'))
    return render_template('new_post.html', title='New Post',
                           form=form, legend='New Post')

@main.route("/post/<int:post_id>")
@login_required
def mypost(post_id):
    comments = Comment.query.filter_by(post_id=post_id).all()
    print(comments)
    heading = 'comments'
    post = Post.query.get_or_404(post_id)
    return render_template('posts.html', title=post.title, post=post, comments=comments, heading=heading)

@main.route('/comment/<post_id>', methods=['Post', 'GET'])

def comment(post_id):
    comment = request.form.get('newcomment')
    new_comment = Comment(comment=comment, user_id=current_user._get_current_object().id, post_id=post_id)
    new_comment.save()
    return redirect(url_for('main.mypost', post_id=post_id))

app/views.py
from flask import render_template
from app import app

# Views
@app.route('/')
def index():

    '''
    View root page function that returns the index page and its data
    '''
    title='Quotes Blog'
    return render_template('index.html',title=title)

app/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        {% if title %}
        <title> {{ title }}</title>
        {% else %}
        <title> Quote Blog </title>
        {% endif %}
    </head>
    <body>
        

        {% extends 'bootstrap/base.html'%}

        <!-- Navbar block  --> 
        {% block navbar %}
        {% include 'navbar.html' %}
        {% endblock %}
        <!-- Content block -->
    </body>
</html>

app/templates/display_comment_macro.html
{% extends 'base.html' %}
{% macro display_comments(comments) %}
<div class="mt-5">
    <h1 class="text-center">Comments</h1>
    {% for comment in comments %}
    <img class="rounded-circle article-img"
         src="{{ url_for('static', filename='profile_pic/' + comment.author.image_file) }}">
    <a class="mr-2 commentname" href="#">Comment by: {{ comment.author.username }}</a>
    <p class="mt-10 mr-2 commentcomment">Comment: {{comment.comment}}</p>
    {% endfor %}
</div>
{% endmacro %}

app/templates/display_post_macro.html
{% macro display_posts(posts)%}
<div>
    {% for post in posts%}
    <article class="media content-section">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="#">{{ post.user_id }}</a>
                <!--                <small class="text-muted">{{ post.title }}</small>-->
            </div>
            <h2><a class="article-title" href="#">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
        </div>
    </article>
    {% endfor%}
</div>
{%endmacro%}

app/templates/display_quote_macro.html
{% macro display_quotes(quotes)%}
<div class="jumbotron">
    <h1 class="text-danger">Random Quotes:</h1>
    <h5 class="mt-3 text-success">{{quotes.quote}}</h5>
    <p>~ {{quotes.author}}</p>
</div>
{%endmacro%}

app/templates/error.html
{% extends 'base.html'%}

{% block content %}
    <h1>WHOOOPS we can't find that page</h1>
{% endblock %}

app/templates/index.html
{% extends 'base.html'%}
{%from 'display_quote_macro.html' import display_quotes%}
{% from 'display_post_macro.html' import display_posts%}
<!-- Styles block -->

{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock %}
<!-- Content block -->

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
       
        <title> {{ title }}</title>
       
    </head>
    <body>
        {% block content %}
<div class='container'>
       
       <h1>Welcome to my Quote Blog</h1>
       <h2>{{display_quotes(quotes)}}</h2>

</div>      
       {% for post in posts %}
<div class='container'>
<article class="media content-section">
    <img class="rounded-circle article-img"
         src=
    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="#">{{ post.author.username }}</a>
            <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
        </div>
        <h2><a class="article-title" href="{{ url_for('main.mypost', post_id=post.id) }}">{{ post.title }}</a></h2>
        <p class="article-content">{{ post.content }}</p>
    </div>
</article>
</div>
{% endfor %}
      
       {% endblock%}
    </body>
</html>

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"> Quote Blog</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">Home</a></li>
        </div>
        <ul class="nav navbar-nav navbar-right">
            <li><a class="nav-item nav-link" href="{{ url_for('main.new_post') }}">New Post</a></li>
            {% if current_user.is_authenticated %}
            <li style="color:white;padding:15px;">{{current_user.username}}</li>
            <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
            {% else %}
            <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
            {%endif%}
          </ul>
        
    </div>
</div>

app/templates/new_post.html
{% extends 'base.html' %}

{% import 'bootstrap/wtf.html' as wtf %}

{% block content%}
    <div class="container">
        <a href="{{url_for('main.index')}}">
                <button type="button" class="btn btn-primary btn-sm" style="margin-bottom:10px;">
                        <span class="glyphicon glyphicon-chevron-left" ></span> Back
                </button>
        </a>
        {{wtf.quick_form(form)}}
    </div>

   
{% endblock %}

app/templates/post.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf%}
{% from 'display_comment_macro.html' import display_comments as commentDisplay%}
{% block content %}
<article class="media content-section">
    <img class="rounded-circle article-img"
         src="{{ url_for('static', filename='profile_pic/' + post.author.image_file) }}">
    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="#">{{ post.author.username }}</a>
            <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            <div>
                <button class="btn btn-info btn-sm m-1" data-target="#commentModal" data-toggle="modal" type="button">
                    Comment
                </button>
                {% if post.author == current_user %}
                <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('main.update_post', post_id=post.id) }}">Update</a>
                <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">
                    Delete
                </button>
                {% endif %}
            </div>
        </div>
        <h2 class="article-title">{{ post.title }}</h2>
        <p class="article-content">{{ post.content }}</p>
    </div>
</article>

<article class="media content-section">
    <div class="media-body">
        <div class="article-metadata">
            <h1>{{commentDisplay(comments)}}</h1>
        </div>
    </div>
</article>
<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <form action="{{ url_for('main.delete_post', post_id=post.id) }}" method="POST">
                    <input class="btn btn-danger" type="submit" value="Delete">
                </form>
            </div>
        </div>
    </div>
</div>
<!-- Modal -->
<div class="modal fade" id="commentModal" tabindex="-1" role="dialog" aria-labelledby="commentModalTitle"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="commentModalTitle">Comment</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="POST" action="{{url_for('main.comment',post_id = post.id)}}">
                    <div class="form-group">
                        <label for="title" class="col-form-label">Title:</label>
                        <input type="text" class="form-control" id="title">
                    </div>
                    <div class="form-group">
                        <label for="comment" class="col-form-label">Comment:</label>
                        <textarea class="form-control" id="comment" name="newcomment"></textarea>
                    </div>


                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Add Comment</button>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

app/templates/posts.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf%}
{% from 'display_comment_macro.html' import display_comments as commentDisplay%}
{% block content %}
<article class="media content-section">
    <img class="rounded-circle article-img"
         src="{{ url_for('static', filename='profile_pic/'}}">
    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="#">{{ post.author.username }}</a>
            <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            <div>
                <button class="btn btn-info btn-sm m-1" data-target="#commentModal" data-toggle="modal" type="button">
                    Comment
                </button>
                {% if post.author == current_user %}
                <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('main.update_post', post_id=post.id) }}">Update</a>
                <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">
                    Delete
                </button>
                {% endif %}
            </div>
        </div>
        <h2 class="article-title">{{ post.title }}</h2>
        <p class="article-content">{{ post.content }}</p>
    </div>
</article>

<article class="media content-section">
    <div class="media-body">
        <div class="article-metadata">
            <h1>{{commentDisplay(comments)}}</h1>
        </div>
    </div>
</article>
<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <form action="{{ url_for('main.delete_post', post_id=post.id) }}" method="POST">
                    <input class="btn btn-danger" type="submit" value="Delete">
                </form>
            </div>
        </div>
    </div>
</div>
<!-- Modal -->
<div class="modal fade" id="commentModal" tabindex="-1" role="dialog" aria-labelledby="commentModalTitle"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="commentModalTitle">Comment</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="POST" action="{{url_for('main.comment',post_id = post.id)}}">
                    <div class="form-group">
                        <label for="title" class="col-form-label">Title:</label>
                        <input type="text" class="form-control" id="title">
                    </div>
                    <div class="form-group">
                        <label for="comment" class="col-form-label">Comment:</label>
                        <textarea class="form-control" id="comment" name="newcomment"></textarea>
                    </div>


                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Add Comment</button>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}